### ISSUE TITLE
CPAN::Mirror::Tiny::Util is missing, CPAN::Mirror::Tiny::CLI is broken

### ISSUE THREAD

**Issue by viy2** [skaji/CPAN-Mirror-Tiny#12]
CPAN::Mirror::Tiny::CLI use CPAN::Mirror::Tiny::Util which was present in 0.20 but is missing now.

**Comment by skaji** [comment]
@viy2 Thanks for reporting this. Fixed in https://metacpan.org/release/SKAJI/CPAN-Mirror-Tiny-0.31

**Comment by viy2** [comment]
Thanks!
