### ISSUE TITLE
Multiple module versions result in non-standard 02packages.details.txt.gz

### ISSUE THREAD

**Issue by maxhq** [skaji/CPAN-Mirror-Tiny#3]
If two versions of the same module are injected...

```
use CPAN::Mirror::Tiny;
my $m = CPAN::Mirror::Tiny->new(base => "$ENV{HOME}/darkpan");
$m->inject("./My-Module-0.1.tar.gz");
$m->inject("./My-Module-0.2.tar.gz");
$m->write_index(compress=>1);
```

...they will both be listed in 02packages.details.txt.gz

```
$ gunzip -c ~/darkpan/modules/02packages.details.txt.gz
Written-By: CPAN::Mirror::Tiny 0.02

My::Module                         v0.1  V/VE/VENDOR/My-Module-0.1.tar.gz
My::Module                         v0.2  V/VE/VENDOR/My-Module-0.2.tar.gz
```

Installing the latter version using e.g. `cpanm --mirror ~/darkpan --mirror-only My::Module~0.2` then fails as `cpanm` only sees the first version.

**Comment by skaji** [comment]
Thank you for your reporting. I will address this issue.

**Comment by skaji** [comment]
Released https://metacpan.org/release/SKAJI/CPAN-Mirror-Tiny-0.05

**Comment by maxhq** [comment]
Wow, that was fast! Thank you very much, also for this useful module generally.
