### ISSUE TITLE
CPAN::Mirror::Tiny::Server::uploader broken

### ISSUE THREAD

**Issue by tehmoth** [skaji/CPAN-Mirror-Tiny#8]
In https://github.com/skaji/CPAN-Mirror-Tiny/commit/fd8778bcef7951cbb49edd808b42026e04ed253d#diff-9530945a06625aeb5bc5e90918d9c76cea8edd448f6773deb07f9efbdc9a0b57 (one of the commits between 0.12 and 0.20) the use of 'overload' was removed from CPAN::Mirror::Tiny::Tempdir, resulting in the following error:
Unknown url CPAN::Mirror::Tiny::Tempdir=HASH(0x5695e6b22998)/Dist-Name-0.01.tar.gz when using, f.e. cpan-upload-tiny
Reverting to version 0.12, or changing line 34 in  CPAN/Mirror/Tiny/Server.pm to
                     $module = File::Spec->catfile($tempdir->as_string, $upload->filename);

**Comment by skaji** [comment]
> Unknown url CPAN::Mirror::Tiny::Tempdir=HASH(0x5695e6b22998)/Dist-Name-0.01.tar.gz 

@tehmoth  Can you provide actual command to reproduce this error?

**Comment by tehmoth** [comment]
> > Unknown url CPAN::Mirror::Tiny::Tempdir=HASH(0x5695e6b22998)/Dist-Name-0.01.tar.gz
> 
> @tehmoth Can you provide actual command to reproduce this error?

$ cpan-mirror-tiny server &
$ cpan-upload-tiny Dist-Name-0.01.tar.gz
(error was output by the cpan-mirror-tiny process)

**Comment by skaji** [comment]
@tehmoth Thank you.
Fixed in https://metacpan.org/release/SKAJI/CPAN-Mirror-Tiny-0.30
